include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
#ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/max1187x/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/max1187x/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  max1187x.o


