--- drivers/staging/Makefile
+++ drivers/staging/Makefile
@@ -59,6 +59,4 @@ obj-$(CONFIG_FIREWIRE_SERIAL)	+= fwserial/
 obj-$(CONFIG_ZCACHE)		+= zcache/
 obj-$(CONFIG_GOLDFISH)		+= goldfish/
 obj-$(CONFIG_USB_DWC2)		+= dwc2/
-
-obj-$(CONFIG_PRIMA_WLAN) += prima/
-obj-$(CONFIG_PRONTO_WLAN) += prima/
+obj-$(CONFIG_PRONTO_WLAN)	+= prima/
